### ISSUE TITLE
Hyper-parameters

### ISSUE THREAD

**Issue by vellichorw** [gaozhengqing/UniEnt#1]
What are the best \labmda_1 and \labmda_2 for UniEnt and UniEnt+ on CIFAR-10-C/CIFAR-100-C/Tiny-ImageNet-C?

**Comment by gaozhengqing** [comment]
Please refer to this table.
![tab_hyperparameter](https://github.com/user-attachments/assets/9771d91d-702c-46f7-9d3f-d574cd50287a)
