### ISSUE TITLE
RuntimeError: Numpy is not available

### ISSUE THREAD

**Issue by andylws** [gaozhengqing/UniEnt#2]
Hello,

Thanks for making this project available, it’s been super helpful! I'm currently running into an issue related to CUDA version.
Could you share the details of the environment you used, like the package versions and any specific settings or dependencies? It would help a lot to make sure I'm replicating your setup correctly.

Thanks again for your great work and looking forward to your response!

**Comment by gaozhengqing** [comment]
All of our experiments were run on an NVIDIA RTX A6000 GPU with CUDA version 11.6. Please refer to [requirements.txt](https://github.com/gaozhengqing/UniEnt/blob/master/requirements.txt) for more details about packages. By the way, please try using NumPy 1.xx.
